baseURL = 'https://example.org/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'Pergaminhos Secretos'

[params]
mainSections = ["beast"]

[params.sidebar]
subtitle = "Conteúdo não oficial do Arcana Primária."

[params.colorScheme]
toggle = false
default = "dark"

[params.article]
license.enabled = true

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

## Widgets
[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'