baseURL = 'https://example.org/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'Oficina Arcana'
theme = 'stack'

[params]
mainSections = ["post"]

[params.sidebar]
subtitle = "Em torres escusas, debruçados sobre mesas fracamente iluminadas, mestres arcanos se deleitam em suas criações enquanto dobram a realidade conforme sua vontade."

[params.colorScheme]
toggle = false
default = "dark"

## Widgets
[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
