import {Spell} from '../types';

const spellList: Spell[] = [
    {"circle": 1, "name": "Benção da Providência", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Círculo de Fé", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Comando", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Criar Água", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Curar Ferimentos Leves", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Detectar Magia", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Estancar Sangramento", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Nervos de Aço", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Purificar Heresia", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Santuário", "ref": null, "listName": "clerigo"},
    {"circle": 1, "name": "Vocação Marcial", "ref": null, "listName": "clerigo"},

    { "circle": 2, "name": "Augúrio", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Benção de Ilych I", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Cântico", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Cativar", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Criar Água Benta", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Glória da Batalha", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Imobilizar Criaturas", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Ímpeto Indômito", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Lâmina Flamejante", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Martelo Espiritual", "ref": null, "listName": "clerigo" },
    { "circle": 2, "name": "Mártir", "ref": null, "listName": "clerigo" },

    { "circle": 3, "name": "Andar sobre Água", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Andar sobre Brasas", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Clamor Radiante", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Criar Alimentos", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Curar Doenças", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Desafio de Ulandor", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Dissipar Magia", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Ídolo de Friedkin", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Localizar Objetos", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Luz Contínua", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Remover Maldição", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Remover Paralisia", "ref": null, "listName": "clerigo" },
    { "circle": 3, "name": "Símbolo de Proteção", "ref": null, "listName": "clerigo" },

    { "circle": 4, "name": "Abjurar", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Avatar Mitológico", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Benção de Ilych II", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Curar Ferimentos Graves", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Detectar Mentiras", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Dogma Ensandecido", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Poça Reflexiva", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Relâmpago Divino", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Sacrifício Heroico", "ref": null, "listName": "clerigo" },
    { "circle": 4, "name": "Terra Santa", "ref": null, "listName": "clerigo" },

    { "circle": 5, "name": "Coluna de Chamas", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Comunhão", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Curar Ferimentos Críticos", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Mudança de Plano", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Nuvem de Purificação", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Serpentes de Mercúrio", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Tridente de Nereus", "ref": null, "listName": "clerigo" },
    { "circle": 5, "name": "Visão da Verdade", "ref": null, "listName": "clerigo" },

    { "circle": 6, "name": "Ciclone Radiante", "ref": null, "listName": "clerigo" },
    { "circle": 6, "name": "Cura Completa", "ref": null, "listName": "clerigo" },
    { "circle": 6, "name": "Oração Restauradora", "ref": null, "listName": "clerigo" },
    { "circle": 6, "name": "Partir Água", "ref": null, "listName": "clerigo" },
    { "circle": 6, "name": "Proibição", "ref": null, "listName": "clerigo" },
    { "circle": 6, "name": "Urro dos Titãs", "ref": null, "listName": "clerigo" },

    { "circle": 7, "name": "Amparo Divino", "ref": null, "listName": "clerigo" },
    { "circle": 7, "name": "Benção de Ilych III", "ref": null, "listName": "clerigo" },
    { "circle": 7, "name": "Praga de Gafanhotos", "ref": null, "listName": "clerigo" },
    { "circle": 7, "name": "Regeneração", "ref": null, "listName": "clerigo" },
    { "circle": 7, "name": "Santa Inquisição", "ref": null, "listName": "clerigo" },
    { "circle": 7, "name": "Tempestade de Fogo", "ref": null, "listName": "clerigo" },
];

export default spellList;