import { Spell } from '../types';

const spellList: Spell[] = [
    { "circle": 1, "name": "Aguentar Frio/Calor", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Amizade Animal", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Arma Totêmica", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Criar Fogo Místico", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Cura Herbal", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Dança Aquática de Lifía", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Enxame de insetos", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Fogo de Fada", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Invisibilidade contra Animais", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Lançar Esporos", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Máscara Selvagem", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Poção Repulsiva", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Saber Direção", "ref": null, "listName": "druida" },
    { "circle": 1, "name": "Tremor", "ref": null, "listName": "druida" },

    { "circle": 2, "name": "Abraço de Sucuri", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Detectar Armadilhas", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Dissolver Teias", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Enraizar", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Espírito Benigno", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Foco Solar/Lunar", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Fruto Ancestral", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Localizar Animais ou Plantas", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Lufada de Vento", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Mirada Bestial", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Pele de Pedra", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Remover Rastros", "ref": null, "listName": "druida" },
    { "circle": 2, "name": "Remover Venenos e Doenças", "ref": null, "listName": "druida" },

    { "circle": 3, "name": "Amplificar Transformação", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Camuflagem", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Chamado do Relâmpago", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Crescer Espinhos", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Força da Natureza", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Moldar Madeira", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Muralha de Vinhas", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Pele Espinhosa", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Poção da Dor", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Respiração Subaquática", "ref": null, "listName": "druida" },
    { "circle": 3, "name": "Santuário Feérico", "ref": null, "listName": "druida" },

    { "circle": 4, "name": "Comunhão Ancestral", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Conjurar Animal Espiritual", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Cura Herbal Maior", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Leque Venenoso", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Mesclar-se com Névoa", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Oração dos Ventos", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Poção de Baiacu", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Ponte de Vinhas", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Tempestade de Granizo", "ref": null, "listName": "druida" },
    { "circle": 4, "name": "Transferir Veneno", "ref": null, "listName": "druida" },

    { "circle": 5, "name": "Âmbar Explosivo", "ref": null, "listName": "druida" },
    { "circle": 5, "name": "Andar sobre Nuvens", "ref": null, "listName": "druida" },
    { "circle": 5, "name": "Árvore da Vida", "ref": null, "listName": "druida" },
    { "circle": 5, "name": "Barragem Solar/Lunar", "ref": null, "listName": "druida" },
    { "circle": 5, "name": "Dádiva da Vida", "ref": null, "listName": "druida" },
    { "circle": 5, "name": "Poção Protetora", "ref": null, "listName": "druida" },
    { "circle": 5, "name": "Terreno Movediço", "ref": null, "listName": "druida" },

    { "circle": 6, "name": "Aspecto Alfa", "ref": null, "listName": "druida" },
    { "circle": 6, "name": "Árvores Guerreiras", "ref": null, "listName": "druida" },
    { "circle": 6, "name": "Gêiser", "ref": null, "listName": "druida" },
    { "circle": 6, "name": "Mover Terreno", "ref": null, "listName": "druida" },
    { "circle": 6, "name": "Restauração Absoluta", "ref": null, "listName": "druida" },
    { "circle": 6, "name": "Sintonia Colossal", "ref": null, "listName": "druida" },

    { "circle": 7, "name": "Deslizamento", "ref": null, "listName": "druida" },
    { "circle": 7, "name": "Erupção", "ref": null, "listName": "druida" },
    { "circle": 7, "name": "Fúria dos Ventos", "ref": null, "listName": "druida" },
    { "circle": 7, "name": "Polimorfismo Floral", "ref": null, "listName": "druida" },
    { "circle": 7, "name": "Terremoto", "ref": null, "listName": "druida" },
    { "circle": 7, "name": "Transformação Jurássica", "ref": null, "listName": "druida" },
];

export default spellList;