import { Spell } from '../types';

const spellList: Spell[] = [
    { "circle": 1, "name": "Armadilha de Plumbus", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Assassino Irreal", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Comando", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Detectar Ilusão", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Disfarçar", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Feixe de Luz", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Força Fantasmagórica", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Névoa Ilusória", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Olhar Refletido", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Provocação", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Som Ilusório", "ref": null, "listName": "ilusionista" },
    { "circle": 1, "name": "Ventriloquismo", "ref": null, "listName": "ilusionista" },

    { "circle": 2, "name": "Boca Mágica", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Canhão de Luz", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Cegueira", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Detectar Invisibilidade", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Desinformar", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Embaçar", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Imagens Espelhadas", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Invisibilidade", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Ouro dos Tolos", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Padrão Hipnótico", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Pesadelo de Insetos", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Piada Mortal", "ref": null, "listName": "ilusionista" },
    { "circle": 2, "name": "Serpentes de Ilinev", "ref": null, "listName": "ilusionista" },

    { "circle": 3, "name": "Aspecto Fantasmagórico", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Aspecto Vegetal", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Assassino Fantasmagórico", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Canto de Álamos", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Disco Umbral", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Dissipar Ilusão", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Escrita Ilusória", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Estátuas Vivas de Plumbus", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Força Espectral", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Invisibilidade 10’ radiais", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Montaria Fantasmagórica", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Servo Invisível", "ref": null, "listName": "ilusionista" },
    { "circle": 3, "name": "Terreno Alucinatório", "ref": null, "listName": "ilusionista" },

    { "circle": 4, "name": "Abandono", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Blefe Ilusório", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Confusão", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Criaturas Sombrias", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Invisibilidade Melhorada", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Mascarar Exaustão", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Medo", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Modificar Aparência em Grupo", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Parede Ilusória", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Portal Ilusório", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Golpe Sônico", "ref": null, "listName": "ilusionista" },
    { "circle": 4, "name": "Repelir", "ref": null, "listName": "ilusionista" },

    { "circle": 5, "name": "Arcana Sombria", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Criaturas das Trevas", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Clausura Umbral", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Emoção", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Eviscerador Fantasmagórico", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Imagens do Passado", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Matilha de Kothrall", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Pesadelo Labiríntico", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Projeção Umbral", "ref": null, "listName": "ilusionista" },
    { "circle": 5, "name": "Sonho", "ref": null, "listName": "ilusionista" },

    { "circle": 6, "name": "Armadilha de Espelhos", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Carruagem Fantasmagórica", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Chave Mestra", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Mente Dupla", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Exércitos Esquecidos de Zandar", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Ilusão Programada", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Miragem de Cristal", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Rajada Sônica", "ref": null, "listName": "ilusionista" },
    { "circle": 6, "name": "Visão da Verdade", "ref": null, "listName": "ilusionista" },

    { "circle": 7, "name": "Espetáculo de Ilinev", "ref": null, "listName": "ilusionista" },
    { "circle": 7, "name": "Explosão Sônica", "ref": null, "listName": "ilusionista" },
    { "circle": 7, "name": "Invisibilidade em Massa", "ref": null, "listName": "ilusionista" },
    { "circle": 7, "name": "Lâminas Sônicas", "ref": null, "listName": "ilusionista" },
    { "circle": 7, "name": "Palavra de Poder: Atordoar", "ref": null, "listName": "ilusionista" },
    { "circle": 7, "name": "Permear Umbra", "ref": null, "listName": "ilusionista" },
    { "circle": 7, "name": "Zona Factual", "ref": null, "listName": "ilusionista" },

    { "circle": 8, "name": "Anomalia Desintegradora", "ref": null, "listName": "ilusionista" },
    { "circle": 8, "name": "Canto das Serpentes", "ref": null, "listName": "ilusionista" },
    { "circle": 8, "name": "Dragão Umbral", "ref": null, "listName": "ilusionista" },
    { "circle": 8, "name": "Extinção", "ref": null, "listName": "ilusionista" },
    { "circle": 8, "name": "Teletransporte Ilusório", "ref": null, "listName": "ilusionista" },
    { "circle": 8, "name": "Tentáculos do Abismo", "ref": null, "listName": "ilusionista" },

    { "circle": 9, "name": "Vibrato", "ref": null, "listName": "ilusionista" },
    { "circle": 9, "name": "Ilusão Interplanar", "ref": null, "listName": "ilusionista" },
    { "circle": 9, "name": "Os Próprios Deuses", "ref": null, "listName": "ilusionista" },
    { "circle": 9, "name": "Palácio de Cristal", "ref": null, "listName": "ilusionista" },
];

export default spellList;