import { Spell } from '../types';

const spellList: Spell[] = [
    { "circle": 1, "name": "Adagas do Desespero", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Afetar Reação", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Alarme Psicológico", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Alterar Percepção", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Animar Pequenos Objetos", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Corpo Metafísico", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Enfeitiçar Criaturas", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Escudo Mental", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Fogo Epistêmico", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Saber Direção", "ref": null, "listName": "psionico" },
    { "circle": 1, "name": "Telepatia Menor", "ref": null, "listName": "psionico" },

    { "circle": 2, "name": "Arrombar", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Barreira Protetora", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Confusão Imediata", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Evasão Premeditada", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Infligir Dor", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Influenciar Barganha", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Leveza de Piskor", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Método de Khalaz’dor", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Percepção Extra-Sensorial", "ref": null, "listName": "psionico" },
    { "circle": 2, "name": "Reduzir Resistência", "ref": null, "listName": "psionico" },

    { "circle": 3, "name": "Armadilha Mental", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Causar Fadiga", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Choque Psíquico", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Detectar Intenção", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Estrangular", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Exame de Lyara", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Influenciar Golpe", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Infravisão", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Interceptar Mensagem", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Método Sicário", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Projeção Sensorial", "ref": null, "listName": "psionico" },
    { "circle": 3, "name": "Vácuo de Brotmandel", "ref": null, "listName": "psionico" },

    { "circle": 4, "name": "Conter Energia", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Defletir Projétil", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Detecção Íntima", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Ejeção", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Gatilho Transportador", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Interceptar Magia", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Levitar", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Previsão I", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Salto entre Mentes", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Transe Regenerativo", "ref": null, "listName": "psionico" },
    { "circle": 4, "name": "Visões do Passado", "ref": null, "listName": "psionico" },

    { "circle": 5, "name": "Campo de Estase", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Destino Ligado", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Imobilizar Monstros", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Remover Habilidade", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Telecinese I", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Telepatia Maior", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Transferir Capacidade", "ref": null, "listName": "psionico" },
    { "circle": 5, "name": "Visão de Basilisco", "ref": null, "listName": "psionico" },

    { "circle": 6, "name": "Animar Grandes Objetos", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Criar Objetos", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Detonação Telecinética", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Fluidez de Espírito", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Rearranjo Molecular", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Reordenação de Alakros", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Repulsão", "ref": null, "listName": "psionico" },
    { "circle": 6, "name": "Vitrificação", "ref": null, "listName": "psionico" },

    { "circle": 7, "name": "Apagar Memória", "ref": null, "listName": "psionico" },
    { "circle": 7, "name": "Arremesso de Mallor", "ref": null, "listName": "psionico" },
    { "circle": 7, "name": "Bombardeio Telecinético", "ref": null, "listName": "psionico" },
    { "circle": 7, "name": "Cirurgia Psíquica", "ref": null, "listName": "psionico" },
    { "circle": 7, "name": "Influenciar Feitiço", "ref": null, "listName": "psionico" },
    { "circle": 7, "name": "Morada do Absoluto", "ref": null, "listName": "psionico" },
    { "circle": 7, "name": "Reverter Magia", "ref": null, "listName": "psionico" },

    { "circle": 8, "name": "Colapsar Estrutura", "ref": null, "listName": "psionico" },
    { "circle": 8, "name": "Controlar Corpo e Mente", "ref": null, "listName": "psionico" },
    { "circle": 8, "name": "Copiar e Transferir Mente", "ref": null, "listName": "psionico" },
    { "circle": 8, "name": "Desmembramento", "ref": null, "listName": "psionico" },
    { "circle": 8, "name": "Dilatação Arcana", "ref": null, "listName": "psionico" },
    { "circle": 8, "name": "Telecinese II", "ref": null, "listName": "psionico" },

    { "circle": 9, "name": "Abismo de Aggaorn", "ref": null, "listName": "psionico" },
    { "circle": 9, "name": "Alterar Espaço-Tempo", "ref": null, "listName": "psionico" },
    { "circle": 9, "name": "Forma ideal", "ref": null, "listName": "psionico" },
    { "circle": 9, "name": "Multiverso", "ref": null, "listName": "psionico" },
    { "circle": 9, "name": "Previsão II", "ref": null, "listName": "psionico" },
];

export default spellList;