let locationKeys = [
    'Platô(s)',
    'Escarpa(s)',
    'Canyon(s)',
    'Rochedo(s)',
    'Vale(s)',
    'Floresta(s)',
    'Charneca(s)',
    'Chaparral(s)',
    'Deserto(s)',
    'Estepe(s)',
    'Planície(s)',
    'Penhasco(s)',
    'Pasto(s)',
    'Ravina(s)',
    'Colina(s)',
    'Pântano(s)',
    'Pradaria(s)',
    'Lago(s)',
    'Montanha(s)',
    'Atoleiro(s)',
    'Ermo(s)',
    'Garganta(s)',
    'Devastação(s)',
    'Pedregulho(s)',
    'Espiral(s)',
    'Caverna(s)',
    'Fosso(s)',
    'Pedra(s)',
    'Campo(s)',
    'Cruzamento(s)',
    'Cidade(s)',
    'Vila(s)',
    'Local(is)',
    'Cemitério(s)',
    'Mosteiro(s)',
    'O Fim/Os fins',
    'Rio(s)',
    'Ruína(s)',
    'Santuário(s)',
    'Mina(s)',
    'Monte(s)',
    'Esconderijo(s)',
    'Fazenda(s)',
    'Forte(s)',
    'Poço(s)',
    'Barreira(s)',
    'Estrada(s)',
    'Barricada(s)',
    'Acampamento(s)',
    'Passagem(s)',
    'Galeria(s)',
    'Riacho(s)',
    'Lagoa(s)',
    'Ponte(s)',
    'Cordilheira(s)',
    'Gêiser(es)',
    'Muralha(s)',
    'Trilha(s)',
    'Espinheiro(s)',
    'Corredeira(s)',
    'Entreposto(s)',
    'Paragem(ns)',
    'Rampa(s)',
    'Baluarte(s)',
    'Bosque(s)',
    'Fileira(s)',
    'Planalto(s)',
    'Cerrado(s)',
    'Calabouço(s)',
    'Ponto(s)',
    'Salina(s)',
    'Paço(s)',
    'Cratera(s)',
    'Meseta(s)',
    'Desfiladeiro(s)',
    'Nascente(s)',
    'Estreito(s)',
    'Saliência(s)',
    'Brejo(s)',
    'Escavação(s)',
    'Buraco(s)',
    'Cachoeira(s)',
    'Círculo(s)',
    'Caminho(s)',
    'Morada(s)',
    'Assentamento(s)',
    'Cabana(s)',
    'Taverna (s)',
    'Vau(s)',
    'Hospedaria(s)',
    'Estalagem(s)',
    'Cimeira(s)',
    'Barranco(s)',
    'Cais(s)',
    'Aldeia(s)',
    'Fonte(s)',
    'Monolito(s)',
    'Represa(s)',
    'Totem(ns)',
    'Pedreira(s)',
    'Corrente(s)',
    'Cortina(s)',
    'Costa(s)',
    'Canal(s)',
    'Serra(s)',
    'Fontes Termais',
    'Tundra(s)',
    'Abismo(s)',
    'Gruta(s)',
    'Descampado(s)',
    'Marcha(s)',
    'Jardim(ns)',
    'Moinho(s)',
    'Trincheira(s)',
    'Coral(is)',
    'Charco(s)',
    'Lamaçal(is)',
    'Masmorra(s)',
    'Castelo(s)',
    'Areia(s)',
    'Fortaleza(s)',
    'Elevação(ões)',
    'Arquipélago(s)',
    'Mangue(s)',
    'Labirinto(s)',
    'Região(ões)',
    'Casa(s)',
    'Paliçada(s)',
    'Declive(s)',
    'Savana(s)',
    'Necrópole(s)',
    'Povoado(s)',
    'Limiar(es)',
    'Monumento(s)',
    'Morro(s)',
    'Covil(is)',
    'Fornalha(s)',
    'Mansão(ões)',
    'Protetorado(s)',
    'Aurora(s)',
    'Oasis(es)',
    'Torre(s)',
    'Rota(s)',
    'Pluma(s)',
    'Cisterna(s)',
    'Portal(is)',
    'Fenda(s)',
    'Cripta(s)',
    'Fissura(s)',
    'Refúgio(s)',
    'Presságio(s)',
    'Repouso(s)',
    'Profundeza(s)',
    'Bacia(s)',
    'Ilha(s)',
    'Entrada(s)',
    'Citadela(s)',
    'Rastro(s)',
    'Baía(s)',
    'Fiorde(s)',
    'Atol(is)',
    'Terra(s)',
    'Geleira(s)',
    'Circo(s)',
    'Vinhedo(s)',
    'Molde(s)',
    'Boca(s)',
    'Catarata(s)',
    'Obelisco(s)',
    'Pico(s)',
    'Arcada(s)',
    'Coluna(s)',
    'Praia(s)',
    'Alpes(s)',
    'Recife(s)',
    'Pavilhão(es)',
    'Água(s)',
    'Piscina(s)',
    'Charco(s)',
    'Cabo(s)',
    'Península(s)',
    'Sumidouro(s)',
    'Recanto(s)',
    'Estuário(s)',
    'Trono(s)',
    'Túnel(is)',
    'Manto(s)',
    'Mirante(s)',
    'Senda(s)',
    'Selva(s)',
    'Digilência(s)',
    'Tumba(s)',
    'Mato(s)',
    'Aqueduto(s)',
    'Porto(s)',
    'Fano(s)',
    'Mausoléu(s)',
    'Mar(s)',
    'Templo(s)',
    'Desolação(s)',
    'A(s) Tortura(s)',
    'Vulto(s)',
    'O(s) Sonho(s)',
    'Pérola(s)',
    'Árvore(s)',
    'Duna(s)',
    'Matagal(s)',
    'Marco(s)',
    'Horizonte(s)',
    'O(s) Desconhecido(s)',
    'Enigma(s)',
    'A(s) Brasa(s)',
    'A(s) Asa(s)',
    'O(s) Castigo(s)',
    'Moledro(s)',
    'O(s) Ardil(s)',
];

let locationThemes = [
    'da Morte',
    'do(s) Profeta(s)',
    'Estrelado(a/s)',
    'do Tormento',
    'Desolado(a/s)',
    'Vulcânico(a/s)',
    'de/do(s) Fogo(s)',
    'Monstruoso(a/s)',
    'do(s) insano(s)/da insanidade',
    'Amarelo(a/s)',
    'da Angústia',
    'Afogado(a/s)',
    'Fantasma(s)',
    'do(s) Odiado(s)',
    'do(s/)de Gigante(s)',
    'Infernal(is)',
    'das Cinzas',
    'Vermelho(s)',
    'Fragmentado(a/s)',
    'da Salvação',
    'Próspero(a)',
    'Prateado(a/s)',
    'Verde(s)',
    'da(s) Carroça(s)',
    'Quebrado(a/s)',
    'Cruel(is)',
    'de/dos Diamante(s)',
    'Esquecido(a/s)',
    'Borbulhante(s)',
    'de Obsidiana',
    'Selvagem(ns)',
    'Destruído(a/s)',
    'Recluso(a/s)',
    'Ancestral(is)',
    'Nevoento(a/s)',
    'Cinzento(a/s)',
    'Baixo(a/s)',
    'Sombrio(a/s)',
    'Safira',
    'Flutuante(s)',
    'Sagrado(a/s)',
    'do(a/s) Erudito(a/s)',
    'Místico(a/s)',
    'Caudaloso(a/s)',
    'Elevado(a/s)',
    'Impassível(is)',
    'do Destino',
    'Velho(a/s)',
    'do(s) Primeiro(s) Povo(s)',
    'Final(is)',
    'Gorgolejante(s)',
    'Miraginal(is)',
    'Gritante(s)',
    'Congelante(s)',
    'Rústico(a)',
    'da(s) Memória(s)',
    'Interminável(is)',
    'Ilusório(a/s)',
    'Vasto(a/s)',
    'Uivante(s)',
    'da /de Chuva',
    'Cercado(a/s)',
    'Maldito(a/s)',
    'Oculto(a/s)',
    'da Vida',
    'Pacífico(a/s)',
    'Eterno(a/s)',
    'Brutal(is)',
    'de/dos Ossos',
    'de/dos Corpos',
    'Silencioso(a/s)',
    'da(s) Tribo(s)',
    'Escorregadio(a/s)',
    'do(s)/de Dragão/Dragões',
    'Movediço(a/s)',
    'Furioso(a/s)',
    'do(a/s)/de Deus(es/as)',
    'do(s) Necromante(s)',
    'de Ferro',
    ' Secreto(a/s)',
    'Afiado(a/s)',
    'do(s) Espelho(s)',
    'Mortal(is)',
    'de Mármore',
    'Caído(a/s)',
    'Claro(a/s)',
    'Lamacento(a/s)',
    'Primordial(is)',
    'Letal(is)',
    'da(s) Lâmina(s)',
    'Profano(a/s)',
    'Negro(a/s)',
    'de Éter/Etéreo(a/s)',
    'da(s) Caça(s)',
    'da Fronteira',
    'Prismático(a/s)',
    'da Liberdade',
    'Trovejante(s)',
    'Afundado(a/s)',
    'do(s) Enforcado(s)',
    'Barrado(a/s)',
    'Boreal(is)',
    'do(s) Desesperado(s)',
    'Venenoso(a/s)',
    'Reluzente(s)',
    'Perverso(a/s)',
    'Antigo(a/s)',
    'Rachado(a/s)',
    'da(s) Legiaõ(es)',
    'da(s) Besta(s)',
    'do(s) Milagre(s)',
    'Terrível(is)',
    'Proibído(a)',
    'de/dos Cristal(is)',
    'do(s) Peregrino(s)',
    'do(s) Rebelde(s)',
    'Queimado(a/s)',
    'Lendário(a/s)',
    'Perdido(a/s)',
    'da(s) Agulha(s)',
    'Isolado(a/s)',
    'da(s) Espada(s)',
    'do(s) Gafanhoto(s)',
    'do(s) Grito(s)',
    'do(s) Pregador(es)',
    'do(s) Duelo(s)',
    'das Nuvens',
    'Novo(a/s)',
    'do(s) Vento(s)',
    'do(s) Mercenário(s)',
    'do(s) Caçador(es)',
    'do(s) Machado(s)',
    'do(s) Barão(ões)',
    'Atordoante(s)',
    'da Patrulha',
    'do(s) Mercador(es)',
    'do(s) Cavaleiro(s)',
    'Branco(a/s)',
    'do(s) Sacerdote(s)',
    'do(s) Guerreiro(s)',
    'do(s) Escudo(s)',
    'Interditado(a/s)',
    'do Abate',
    'da Traição/Traiçoeiro(a/s)',
    'da(s) Aposta(s)',
    'dos Bárbaros',
    'das Neves',
    'do(s) Vigilante(s)',
    'do Luar',
    'da Justiça',
    'do(s) Rei(s) ou da(s) Rainha(s)',
    'do(a) Coroado(a)',
    'do(s) Espectro(s)',
    'do(s) Andarilho(s)',
    'do(s) Imperador(es)',
    'da Fúria',
    'do(s)/de Canibal(is)',
    'da(s) Batalha(s)',
    'Assombrado(s/a/as)',
    'Azul(is)',
    'Invadido(s/a/as)',
    'Abandonado(s/a/as)',
    'do Apocalipse',
    'Vaporoso(s/a/as)',
    'de Bronze',
    'do Ferreiro',
    'do(s)/de Feiticeiro(s)',
    'do(s)/de Pirata(s),',
    'Assolado(s/a/as)',
    'do(s) Duque(s)',
    'da(s) Recompensa(s)',
    'de Sangue',
    'da(s) Tragédia(s)',
    'da(s) Graça(s)',
    'do(a/s) Procurado(a/s)',
    'Árido(a/s)',
    'Inominável(is)',
    'da(s) Praga(s)',
    'Estranho(a/s)',
    'do(s) Abutre(s)',
    'de/da(s) Víbora(s)',
    ' do(s) Ladrão(ões)',
    'Fúnebre(s)',
    'do(s) Corvo(s)',
    'da(s) Aberração(ões)',
    'da(s) Tempestade(s)',
    'do(s) Carniçal(is)',
    'do(s) Esqueleto(s),',
    'da(s) Lápide(s)',
    'da(s) Aranha(s)',
    'do(s) Diabo(s)',
    'do(s) Verme(s)',
    'Ácido(a/s)',
    'Demoníaco(a/s)',
    'do Caos/Caótico(a/s)',
    'Magenta',
    'Ecoante(s)',
    'do(s) Escorpião(ões)',
    'Subterrâneo(a)',
    'Podre(s)',
    'Cintilante(s)',
    'Encantado(a/s)',
    'de Ébano',
    'Mágico(a/s)',
    'do Massacre',
    'da(s) Alma(s)',
    'da Sabedoria',
    'da(s) Especiaria(s)',
    'Violeta(s)',
    'do(s) Fungo(s)',
    'da(s) Aparição(ões)',
    'da Aurora',
    'Violento(s)',
    'Fétido(a/s)',
    'de Jade',
    'Colossal(is)',
];

export const generateLocation = () => {
    const randomKeyIdx = Math.floor(Math.random() * locationKeys.length);
    const randomThemeIdx = Math.floor(Math.random() * locationThemes.length);

    return `${locationKeys[randomKeyIdx]} ${locationThemes[randomThemeIdx]}`;
};
