import {randomGender, randomName} from "../helper";

const npcCharacteristics = [
    'Religioso',
    'Distraído',
    'Atrapalhado',
    'Bem-sucedido',
    'Pragmático',
    'Cabeludo',
    'Viciado',
    'Adorável',
    'Belo',
    'Aventureiro',
    'Afável',
    'Medroso',
    'Agressivo',
    'Atento',
    'Atraente',
    'Sedutor',
    'Inquieto',
    'Faminto',
    'Ambicioso',
    'Intrigante',
    'Luxuoso',
    'Animado',
    'Anti-social',
    'Ansioso',
    'Apreensivo',
    'Aristocrático',
    'Arrogante',
    'Artístico',
    'Assertivo',
    'Austero',
    'Falta um membro do corpo',
    'Falta um olho',
    'Hostil',
    'Cicatriz estranha',
    'Asqueroso',
    'Infantil',
    'Briguento',
    'Amargo',
    'Exibido',
    'Entediado',
    'Inteligente',
    'Bem-vestido',
    'Bruto',
    'Ocupado',
    'Frio',
    'Calculista',
    'Cuidadoso',
    'Desconfiado',
    'Furtivo',
    'Educado',
    'Brilhante',
    'Comunicativo',
    'Intenso',
    'Resignado',
    'Gentil',
    'Corajoso',
    'Mudo',
    'Cego',
    'Surdo',
    'Sombrio',
    'Mal-vestido',
    'Voz profunda',
    'Voz melódica',
    'Voz estridente',
    'Lunático',
    'Detestável',
    'Digno',
    'Discreto',
    'Elegante',
    'Misterioso',
    'Dogmático',
    'Sonhador',
    'Estúpido',
    'Excêntrico',
    'Egoísta',
    'Perverso',
    'Bondoso',
    'Senil',
    'Ancião',
    'Estranho',
    'Emotivo',
    'Esquálido',
    'Justo',
    'Vulgar',
    'Zombeteiro',
    'Pessimista',
    'Otimista',
    'Beato',
    'Polido',
    'Estudioso',
    'Quieto',
    'Barulhento',
    'Violento',
    'Vulnerável',
    'Venenoso',
    'Gordo',
    'Magro',
    'Forte',
    'Fraco',
    'Organizado',
    'Infeliz',
    'Feliz',
    'Oportunista',
    'Supérfluo',
    'Habilidoso',
    'Racional',
    'Inepto',
    'Lógico',
    'Sutil',
    'Preguiçoso',
    'Lento',
    'Humilde',
    'Sujo',
    'Acadêmico',
    'Fanático',
    'Esnobe',
    'Plebeu',
    'Carente',
    'Corrupto',
    'Jovial',
    'Destituído',
    'Alto',
    'Baixo',
    'Muito Alto',
    'Muito Baixo',
    'Muito Forte',
    'Negligente',
    'Idealista',
    'Revoltado',
    'Brincalhão',
    'Jovem',
    'Triste',
    'Olheiras profundas',
    'Nariz pontudo',
    'Traiçoeiro',
    'Trabalhador',
    'Raso',
    'Combativo',
    'Unhas sujas',
    'Curioso',
    'Mente aberta',
    'Ganancioso',
    'Criminoso',
    'Armado',
    'Bárbaro',
    'Tribal',
    'Estrangeiro',
    'Perdido',
    'Apaixonado',
    'Ferido',
    'Interessante',
    'Investigativo',
    'Faltam alguns dentes',
    'Apático',
    'Inconveniente',
    'Militar',
    'Nobre',
    'Sacerdotal',
    'Mercante',
    'Sério',
    'Careca',
    'Despreocupado',
    'Preocupado',
    'Manco',
    'Corcunda',
    'Esguio',
    'Carrancudo',
    'Sereno',
    'Pensativo',
    'Dócil',
    'Disposto',
    'Indisposto',
    'Solene',
    'Insolente',
    'Doente',
    'Infame',
    'Famoso',
    'Poético',
    'Musical',
    'Conivente',
    'Insensível',
    'Cativante',
    'Feio',
    'Esperto',
    'Louco',
    'Impassível',
    'Tenso',
    'Generoso',
    'Engenhoso',
    'Manipuladoro',
    'Atencioso',
    'Ciumento',
    'Mal-cheiroso',
    'Perfumado',
    'Alerta',
    'Ardiloso',
    'Honroso',
    'Moribundo',
    'Andarilho',
    'Eremita',
    'Missionário',
    'Viajante',
    'Artesão',
    'Mendicante',
    'Aprendiz',
    'Mestre',
    'Mercenário',
    'Muito Gordo',
    'Entorpecido',
    'Motivado',
    'Místico',
    'Prestativo',
    'Teimoso',
    'Obcecado',
    'Cético',
    'Diabólico',
];

interface Npc {
    characteristics: string;
    name: string;
}

const randomCharacteristic = (): string => {
    const index = Math.floor(Math.random() * npcCharacteristics.length);
    return npcCharacteristics[index];
}

export const generateNpc = (): Npc => {
    return {
        characteristics: [
            randomCharacteristic(),
            randomCharacteristic(),
            randomCharacteristic(),
        ].join(', '),
        name: randomName(randomGender()),
    }
}